services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME} # Default database's name
    ports:
      - "5432:5432"
    volumes:
      - ./SQL:/SQL
      - ./uinnovate-test-db-dump.backup:/dumps/uinnovate-test-db-dump.backup # Copies the dump file into the container
      - ./init.sql:/docker-entrypoint-initdb.d/1_init.sql # Create the schemas, the custom views and the web_anon role
      - ./init.sh:/docker-entrypoint-initdb.d/2_init.sh # Populates the application schema with the dump file tables
      - ./grant_access_to_anon.sql:/docker-entrypoint-initdb.d/3_grant_access_to_anon.sql # Grant permissions to web_anon to read tables

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    profiles:
      - tool
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
      PGRST_DB_SCHEMAS: application, meta
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
