services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres 
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /data/postgres
      PGUSER: web_anon
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1_init.sql
      - db_data:/data/postgres
    networks:
      - backend
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    profiles:
      - tool
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - backend

  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
      PGRST_DB_SCHEMAS: application, meta, cron
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
    depends_on:
      - db
    networks:
      - backend
    restart: always

volumes:
  db_data:
    name: db-data
    driver: local

networks:
  backend:
    name: backend
