FROM node:latest as builder

WORKDIR /app

COPY UInnovateApp/package*.json ./
RUN npm install

# problem w copying files; path?
COPY UInnovateApp/ ./ 
# COPY UInnovateApp/ .

RUN npm run build

# Base image for postgoat 
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY /build.conf /etc/nginx/conf.d/build.conf


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


#  DOCKER_BUILDKIT=1 docker build -f Dockerfile.goat -t eg-one .       