FROM node:latest as builder

WORKDIR /app

COPY UInnovateApp/package*.json ./
RUN npm install

# problem w copying files; path?
COPY UInnovateApp/ ./ 
# COPY UInnovateApp/ .

RUN npm run build

# Base image for postgoat 
FROM nginx:alpine
COPY --from=builder /public /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


