site_name: Tool Rental API Documentation
docs_dir: docs
site_dir: site
theme: readthedocs
nav:
  - Home: index.md
  - Diagram: diagram.md
  - Tool Management: tool.md
  - Customer Relationship Management: crm.md
  - Restock and Recalibration: recal.md