name: Build and Publish Docker Image

on:
  push:
    branches:
      - 237-automation-postgoat-image-dockerhub

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull alexicazana/goat-dock

      - name: Tag Docker image
        run: docker tag alexicazana/goat-dock yourdockerhubusername/postgoat-frontend:latest

      - name: Push Docker image to Docker Hub
        run: docker push yourdockerhubusername/postgoat-frontend:latest
