name: Build and Publish Docker Image

on:
  push:
    branches:
      - 237-automation-postgoat-image-dockerhub

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull alexicazana/goat-dock:v1

      - name: Tag Docker image
        run: docker tag alexicazana/goat-dock:v1 mariar001/postgoat-frontend:latest

      - name: Push Docker image to Docker Hub
        run: docker push mariar001/postgoat-frontend:latest
