name: Build and Push Custom Postgres Docker Image to Azure Container Registry
on:
  push:
    branches:
      - 'deployment-test'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
     
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and Push to ACR
        uses: docker/build-push-action@v2
        with:
          build-args: "JWT_SECRET=${{ secrets.JWT_SECRET }}"
          push: true
          tags: ${{ secrets.ACR_URL}}/postgres-custom:latest
          file: Dockerfile.postgres
          


