name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - 143-documentation-deployment
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout UInnovate repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install mkdocs

    - name: Copy .md files from usecase to root documentation
      run: |
        cp UInnovate/documentation/docs/*.md UInnovate/documentation/build_docs/
        ls -R UInnovate/documentation/build_docs/

    - name: Build MkDocs documentation
      working-directory: ./documentation
      run: |
        mkdocs build -d build_docs/
        ls -R ./build_docs/

    - name: Debug MkDocs build output
      run: |
        ls -R ./documentation/build_docs/

    - name: Checkout PostGOAT repository
      uses: actions/checkout@v2
      with:
        repository: MariaR001/PostGOAT
        ref: 'main'
        token: ${{ secrets.POSTGOAT_WEBSITE_REPOSITORY_DEPLOYMENT_SECRET }}

    - name: Copy MkDocs build to PostGOAT repository
      run: |
        mkdir -p PostGOAT/docs  
        cp -r UInnovate/documentation/build_docs/* PostGOAT/docs/
    
    - name: Debug copied files in PostGOAT
      run: |
        ls -R PostGOAT/docs/

    - name: Commit and push changes to PostGOAT
      run: |
        cd PostGOAT
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy MkDocs documentation from UInnovate"
        git push origin HEAD:main