name: Deploy MkDocs Documentation

on:
  push:
    path: './documentation/**'
    branches:
      - 143-documentation-deployment

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
    - name: Checkout UInnovate repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install mkdocs

    - name: Copy .md files from usecase to root documentation
      run: |
        cp database/useCaseOne/*.md ./documentation

    - name: Build MkDocs documentation
      working-directory: ./documentation
      run: |
        mkdocs build -d documentation

    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.2      
      env:
        API_TOKEN_GITHUB: ${{ secrets.POSTGOAT_WEBSITE_REPOSITORY_DEPLOYMENT_SECRET }}
      with:
        source-files: 'documentation'
        destination-username: 'MariaR001'
        destination-repository: 'PostGOAT'
        destination-branch: 'main'
        commit-email: 'ma_iv@live.concordia.ca'

    - name: Commit and Push changes to PostGOAT repository
      run: |
        git config --global user.email "ma_iv@live.concordia.ca"
        git config --global user.name "MariaR001"
        git add .
        git commit -m "Update documentation" || exit 0  # exit 0 to handle case when there are no changes
        git push https://