name: Deploy MkDocs Documentation

on:
  push:
    branches:
      - 143-documentation-deployment

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout UInnovate repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install mkdocs

    - name: Build MkDocs documentation
      working-directory: ./documentation
      run: |
        mkdocs build -d build_docs/

    - name: Checkout PostGOAT repository
      uses: actions/checkout@v2
      with:
        repository: MariaR001/PostGOAT
        path: PostGOAT

    - name: Copy MkDocs build to PostGOAT repository
      run: |
        mkdir -p PostGOAT/docs  
        cp -r ./documentation/build_docs/* PostGOAT/docs/

    - name: Commit and push changes to PostGOAT
      env:
        API_TOKEN_GITHUB: ${{ secrets.POSTGOAT_WEBSITE_REPOSITORY_DEPLOYMENT_SECRET }}
      run: |
        cd PostGOAT
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Deploy MkDocs documentation from UInnovate"
        git push https://$POSTGOAT_WEBSITE_REPOSITORY_DEPLOYMENT_SECRET@github.com/MariaR001/PostGOAT.git HEAD:main
