name: Deploy MkDocs Documentation

on:
  push:
    path: 'documentation/docs/**'
    branches:
      - 143-documentation-deployment

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    env:
      working-directory: ./

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout UInnovate repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install mkdocs

    - name: Copy .md files from usecase to root documentation
      run: |
        cp documentation/docs/*.md ./documentation

    - name: Build MkDocs documentation
      working-directory: ./documentation
      run: |
        mkdocs build -d documentation

    - name: Copy files to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.2      
      env:
        API_TOKEN_GITHUB: ${{ secrets.POSTGOAT_WEBSITE_REPOSITORY_DEPLOYMENT_SECRET }}
      with:
        source-files: 'documentation'
        destination-username: 'MariaR001'
        destination-repository: 'PostGOAT'
        destination-branch: 'main'
        destination-directory: 'docs'
        commit-email: 'ma_iv@live.concordia.ca'
