name: 'Test'
on:
  pull_request:
    branches:
      - main  # Adjust to the appropriate branch name

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./UInnovateApp

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
    - name: 'Install Node'
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: 'Install Deps'
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: 'Run Vitest'
      run: npx vitest --coverage --reporter=json-summary
      working-directory: ${{env.working-directory}}
    - name: 'Report Coverage'
      if: always()
      uses: davelosert/vitest-coverage-report-action@v2
      with:
        vite-config-path: './UInnovateApp/vite.config.js'
