name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      working-directory: ./UInnovateApp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # install dependencies using the root folder
      - name: Install 📦
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: ./UInnovateApp
          build: npm run build
          start: npm start